### ISSUE TITLE
Laravel error when loading the homepage

### ISSUE THREAD

**Issue by Deca** [RootSoft/algoland#1]
Hi,
I'm trying to run the application but getting a `{"message":"Method Not Allowed"} ` on homepage /explore
note: I'm not using the docker project but simply running the laravel web app on a local wamp stack already tested with other laravel projects.

step taken:

- cloned the repo
- installed dependecies with` composer install`
- installed all frontend libs with` npm install`
- compiled with` npm run dev`

![image](https://user-images.githubusercontent.com/3716783/122299338-2607ea00-cefe-11eb-8eaa-d5f02744b840.png)

**Comment by RootSoft** [comment]
Any idea what route you are requesting?
Are you using the default algorand.php file or any other node connection parameters?

**Comment by Deca** [comment]
Hi @RootSoft
It's routing to explore
I managed to get past to that error, simply omitted to add API keys and url endpoint into algorand.php
I've created a purestake account and added testnet urls and my api keys using that structure:
``` return [
    'algod' => [
        'api_url' => 'https://testnet-algorand.api.purestake.io/ps2',
        'api_key' => 'YOUR API KEY',
        'api_token_header' => 'x-api-key',
    ],
    'indexer' => [
        'api_url' => 'https://testnet-algorand.api.purestake.io/idx2',
        'api_key' => 'YOUR API KEY',
        'api_token_header' => 'x-api-key',
    ],
]; 
```

But seems the key is not accepted 

![image](https://user-images.githubusercontent.com/3716783/122574741-45af2780-d050-11eb-862e-b415696b16ab.png)


If I make a GET request to the testnet with curl (as visible in the purestake example) using my key I get a positive result with algoD endpoint but not with the indexer

**Comment by MustafaTaj** [comment]
I have the same problem, i’m getting forbidden error

**Comment by RootSoft** [comment]
Can you guys test with the AlgoExplorer API? Something might have changed in the PureStake API.

```php
<?php

return [
    'algod' => [
        'api_url' => 'https://api.testnet.algoexplorer.io',
    ],
    'indexer' => [
        'api_url' => 'https://api.testnet.algoexplorer.io/idx2',
    ],
];

```

**Comment by MustafaTaj** [comment]
still the same, can you try it
maybe we are doing something wrong

**Comment by MustafaTaj** [comment]
Switching from windows to mac solved the problem,

Is there anyway to transfer the nft from wallet to another ?

**Comment by NatanTechofNY** [comment]
Experiencing the same issue on fresh Laravel install @RootSoft. Tried both the AlgoExplorer API and the PureStake, same issue.

**Comment by RootSoft** [comment]
I think I know what the issue is.
Can you guys require the latest dev branch in your composer.json file and try again?

```
"require": {
    "rootsoft/algorand-php": "dev-develop",
},
```
@MustafaTaj You can transfer an NFT (ASA) using the ```transfer``` method to send an NFT from your account to another one. The account that wants to receive the NFT needs to explicitly opt-in to receive the NFT. See https://github.com/RootSoft/algorand-php/tree/develop#asset-management for more information.

**Comment by Deca** [comment]
with the dev branch I can render the explorer page but there is some issue with livewire

 
![image](https://user-images.githubusercontent.com/3716783/122800622-71861380-d2c3-11eb-95b9-b96829648d61.png)

**Comment by NatanTechofNY** [comment]
Also experiencing this issue when trying to create a new NFT
`{
    "message": "cURL error 7: Failed to connect to host.docker.internal port 5001: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://host.docker.internal:5001/api/v0/add?only-hash=1",
    "exception": "Rootsoft\\IPFS\\Exceptions\\IPFSException",
    "file": "algoland\\vendor\\rootsoft\\laravel-ipfs\\src\\Traits\\MakesHttpRequests.php",
    "line": 93,
}`

**Comment by RootSoft** [comment]
@Deca I think the problem is related to the same issue but on the laravel-ipfs package. Can you also update that to the latest dev branch?

```
"require": {
    "rootsoft/laravel-ipfs": "dev-develop"
},
```

@NatanTechofNY Are you running docker on Windows? The ```ipfs.php``` file in your config directory tries to connect with the ipfs node on the host machine (from sail). I assume you will have to connect with localhost if you are not using docker.

**Comment by lovecoding-git** [comment]
why was this closed?

**Comment by lovecoding-git** [comment]
![image](https://user-images.githubusercontent.com/61916777/143541175-26348fd6-31ce-486e-ab80-f9da33a49fad.png)
