### ISSUE TITLE
An error occured when minting your NFT. Error: Request failed with status code 500

### ISSUE THREAD

**Issue by Z-zzim** [RootSoft/algoland#2]
Hi!
I run IPFS Desktop and status - connected to IPFS.
I have some work addresses:

```
GATEWAY:  http://127.0.0.1:8080
API:  /ip4/127.0.0.1/tcp/5001
```
```
ADDRESSES:
/ip4/127.0.0.1/tcp/4001/p2p/12D3KooWQLpF7fRu8VcsNpxRoHoEwcxXriSpBdopW6BVKPZqQLi1
/ip4/127.0.0.1/udp/4001/quic/p2p/12D3KooWQLpF7fRu8VcsNpxRoHoEwcxXriSpBdopW6BVKPZqQLi1
/ip4/188.164.164.240/tcp/4001/p2p/12D3KooWQLpF7fRu8VcsNpxRoHoEwcxXriSpBdopW6BVKPZqQLi1
/ip4/188.164.164.240/udp/4001/quic/p2p/12D3KooWQLpF7fRu8VcsNpxRoHoEwcxXriSpBdopW6BVKPZqQLi1
/ip4/192.168.1.30/tcp/4001/p2p/12D3KooWQLpF7fRu8VcsNpxRoHoEwcxXriSpBdopW6BVKPZqQLi1
/ip4/192.168.1.30/udp/4001/quic/p2p/12D3KooWQLpF7fRu8VcsNpxRoHoEwcxXriSpBdopW6BVKPZqQLi1
/ip6/::1/tcp/4001/p2p/12D3KooWQLpF7fRu8VcsNpxRoHoEwcxXriSpBdopW6BVKPZqQLi1
/ip6/::1/udp/4001/quic/p2p/12D3KooWQLpF7fRu8VcsNpxRoHoEwcxXriSpBdopW6BVKPZqQLi1
```
But in Chrome Console a completely different address (status code 500) when i try to create an item:
`POST http://192.168.1.190:81/asa/transaction/fields 500 (Internal Server Error)`
`{message: "cURL error 6: Could not resolve host: host.docker.…/host.docker.internal:5001/api/v0/add?only-hash=1", exception: "Rootsoft\\IPFS\\Exceptions\\IPFSException", file: "/var/www/html/vendor/rootsoft/laravel-ipfs/src/Traits/MakesHttpRequests.php", line: 93, trace: Array(50)}`

How should I change the address "host.docker.internal"? I tried to change to 127.0.0.1, but I get 500.
![issue01](https://user-images.githubusercontent.com/46194513/126005148-e1ec98a3-8067-4020-b4fa-06a6a1f28526.jpg)
![issue02](https://user-images.githubusercontent.com/46194513/126005161-714dae86-dfa3-4715-b23b-2a5acf1d2fda.jpg)

**Comment by RootSoft** [comment]
hi @Z-zzim ,

My apologies for the late reply.
Are you using sail/docker with Laravel? 
If not, you should change the base url and port in the ```ipfs.php```.
You have to find the correct ip address (localhost?) and port of your IPFS node.

**Comment by Z-zzim** [comment]
Hi! 
Thanks for your regard!

Yes, I used sail/docker in Linux/Ubuntu but  Linux have no Docker Desktop. I used Docker Engine and Docker compose. 
Address `host.docker.internal` in Linux dont work. I tryed to use `localhost`, `127.0.0.1`, external local address (`192.168.1.190`) and address net from docker (`172.20.16.1`). I used default port: `5001`

I runned Application on MacOs without problems followed your instruction. I used configure by default in Linux and MacOS.

**Comment by kubeworkz** [comment]
Hi:
Did this ever get resolved? I'm getting the same error. (I'm on Ubuntu 18.04)
Cheers,
Dave

**Comment by RootSoft** [comment]
Unfortunaly, I haven't been able to try this out with ubuntu. You'd need to be able to bridge between Docker and your host machine or hook in IPFS in your docker environment.

Another option would be to run using [Homestead](https://laravel.com/docs/8.x/homestead) rather than Sail or migrate IPFS to [Pinata](https://www.pinata.cloud/)

**Comment by kubeworkz** [comment]
Hi:
I have a solution for us. I got it working last night. It requires docker 20.10+. I added `extra_hosts` to docker-compose.yaml:

```
...
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        extra_hosts:
            - "host.docker.internal:172.17.0.1"
...
```
Also, it's a little easier to manage IPFS on Ubuntu from the command-line. So I do: 
```
sudo snap install ipfs
```
Once snap is installed enter the following:
```
ipfs config Addresses.API /ip4/0.0.0.0/tcp/5001
ipfs config Addresses.Gateway /ip4/0.0.0.0/tcp/8080
```
If you login to the running laravel container you can CURL stuff from the host computer.

Linux keeps the loopback port pretty protected. It's just a matter of getting IPFS off 127.0.0.1.

Cheers,
Dave
